import { useState, useRef, useEffect, useMemo } from 'react';
import { Play, Pause, RotateCcw, Sparkles, Volume2, VolumeX, BookOpen, Maximize2, FileText, Lightbulb, CheckCircle2, Activity, Plus } from 'lucide-react';
import { BlockMath, InlineMath } from '../../Math';
import { useSimulationRecorder } from '../../../hooks/useSimulationRecorder';
import { ScientificGraphLab } from '../../graphing/ScientificGraphLab';
import { dopplerEffectGraphs } from '../../graphing/presets';

interface Wavefront {
  id: number;
  x: number;
  y: number;
  radius: number;
  timeElapsed: number;
}

const DOPPLER_THEORY_NOTES = {
  en: {
    badge: 'Waves & Oscillations • Interactive Notebook',
    notebookMode: 'Interactive Notebook',
    simOnlyMode: 'Sim Only Mode',
    tabTheory: 'Theory & Physical Laws',
    tabFormulas: 'Equations & SI Units',
    tabTips: 'A/L Exam Insights',

    dopplerDefTitle: '1. Definition of Doppler Effect',
    dopplerDefBody: 'The apparent change in frequency or wavelength of a wave for an observer moving relative to its source. As a sound source approaches an observer, wave crests arrive closer together in time, producing a higher pitch (higher observed frequency f\'). As it recedes, wave crests arrive farther apart, producing a lower pitch.',

    wavefrontTitle: '2. Wavefront Dynamics & Wavelength Change',
    wavefrontBody: 'When a source moves at speed v_s through a medium with sound speed v:',
    towardsWave: 'Approaching Observer: Wavefronts compress to reduced wavelength λ\' = (v - v_s)/f_s.',
    awayWave: 'Receding Observer: Wavefronts expand to increased wavelength λ\' = (v + v_s)/f_s.',

    sonicBoomTitle: '3. Sonic Boom & Mach Cone (v_s ≥ v)',
    sonicBoomBody: 'When source speed reaches or exceeds the speed of sound:',
    sonicList: [
      'Sonic Barrier (v_s = v, Mach 1): Wavefronts pile up in front of the source to form a high-pressure sound barrier.',
      'Supersonic Flight (v_s > v, Mach > 1): Source outruns its own waves, creating a conical shockwave cone (Mach Cone).',
      'Mach Cone Angle: sin(θ) = v / v_s = 1 / M, where M is the Mach number.'
    ],

    eqTitle: 'Essential Doppler Syllabus Equations & Verbal Meaning',
    generalEq: 'General Doppler Equation:',
    varGuideTitle: 'Variables & SI Units Reference Guide',

    eqExpl: {
      doppler: 'Verbal Meaning: Observed frequency f\' increases when source and observer approach each other (upper signs +, -), and decreases when receding (lower signs -, +).',
      statObs: 'Verbal Meaning: When observer is stationary (v_o = 0), f\' depends purely on sound speed v and source speed v_s.',
      mach: 'Verbal Meaning: Mach number M > 1 means supersonic flight, creating a Mach Cone of half-angle sin(θ) = 1/M.'
    },

    vars: [
      { sym: "f'", name: 'Observed Frequency', unit: 'Hz (s⁻¹)' },
      { sym: 'fs', name: 'Source Frequency', unit: 'Hz (s⁻¹)' },
      { sym: 'v', name: 'Speed of Sound in Medium', unit: 'm/s' },
      { sym: 'vs', name: 'Speed of Source', unit: 'm/s' },
      { sym: 'vo', name: 'Speed of Observer', unit: 'm/s' },
      { sym: 'λ, λ\'', name: 'Actual vs Apparent Wavelength', unit: 'm' },
      { sym: 'M', name: 'Mach Number (vs / v)', unit: 'Dimensionless' },
      { sym: 'θ', name: 'Mach Cone Half-Angle', unit: 'degrees' },
    ],

    tipsTitle: 'G.C.E. A/L Exam Key Insights',
    tips: [
      'Medium Speed Invariance: Speed of sound v depends solely on the properties of the medium (e.g. 340 m/s in air), NOT on the source speed v_s.',
      'Source Frequency Constancy: Source frequency f_s generated by the emitter remains constant; only the APPARENT frequency f\' changes due to relative motion.',
      'Passing Ambulance Frequency Drop: When an ambulance passes a stationary observer, the observed frequency drops instantly from f_approach = f_s v / (v - v_s) to f_recede = f_s v / (v + v_s).'
    ]
  },
  si: {
    badge: 'තරංග සහ දෝලන • අන්තර්ක්‍රියාකාරී සටහන් පොත',
    notebookMode: 'අන්තර්ක්‍රියාකාරී සටහන් පොත',
    simOnlyMode: 'අනුකරණය පමණක්',
    tabTheory: 'සිද්ධාන්ත සහ නියම',
    tabFormulas: 'සමීකරණ සහ ඒකක',
    tabTips: 'උසස් පෙළ විභාග සටහන්',

    dopplerDefTitle: '1. ඩොප්ලර් ආචරණයේ අර්ථ දැක්වීම',
    dopplerDefBody: 'තරංග ප්‍රභවයක් සහ නිරීක්ෂකයෙකු අතර පවතින සාපේක්ෂ චලිතය නිසා නිරීක්ෂකයාට ඇසෙන සංඛ්‍යාතයේ හෝ ධ්වනි ශ්‍රව්‍ය ස්වරයේ සිදුවන ආභාසී වෙනස්වීම ඩොප්ලර් ආචරණය ලෙස හැඳින්වේ. ප්‍රභවය නිරීක්ෂකයා දෙසට පැමිණෙන විට තරංග ශීර්ෂ ළංවී වැඩි සංඛ්‍යාතයක් ඇසේ. ඈතට යනවිට අඩු සංඛ්‍යාතයක් ඇසේ.',

    wavefrontTitle: '2. තරංග ශීර්ෂ සහ තරංග ආයාම වෙනස්වීම',
    wavefrontBody: 'ධ්වනි ප්‍රවේගය v වන මාධ්‍යයක ප්‍රභවය v_s ප්‍රවේගයෙන් චලනය වන විට:',
    towardsWave: 'ළඟාවන නිරීක්ෂකයාට: තරංග ශීර්ෂ තෙරපී තරංග ආයාමය අඩුවේ λ\' = (v - v_s)/f_s.',
    awayWave: 'ඈත්වන නිරීක්ෂකයාට: තරංග ශීර්ෂ ඈත්වී තරංග ආයාමය වැඩිවේ λ\' = (v + v_s)/f_s.',

    sonicBoomTitle: '3. සුපිරිධ්වනි කම්පන තරංග සහ මාක් කෝතුව (v_s ≥ v)',
    sonicBoomBody: 'ප්‍රභවයේ ප්‍රවේගය ධ්වනි ප්‍රවේගයට සමාන හෝ වැඩි වූ විට:',
    sonicList: [
      'ධ්වනි තාප්පය (v_s = v, මාක් 1): ප්‍රභවය ඉදිරියෙන් තරංග ශීර්ෂ එකිනෙක මත පතිත වී අධික පීඩන තාප්පයක් සාදයි.',
      'සුපිරිධ්වනි ගමන (v_s > v, මාක් > 1): ප්‍රභවය ස්වකීය තරංග අභිබවා ගමන් කරමින් කෝතුකාකාර කම්පන තරංගයක් (මාක් කෝතුව) සාදයි.',
      'මාක් කෝතුවේ කෝණය: sin(θ) = v / v_s = 1 / M (මෙහි M යනු මාක් අංකයයි).'
    ],

    eqTitle: 'විෂය නිර්දේශයේ ඩොප්ලර් සමීකරණ සහ ඒවායේ අර්ථය',
    generalEq: 'පොදු ඩොප්ලර් සමීකරණය:',
    varGuideTitle: 'පරාමිතීන් සහ SI ඒකක නාමාවලිය',

    eqExpl: {
      doppler: 'වචනාර්ථය: ප්‍රභවය සහ නිරීක්ෂකයා එකිනෙකට ළඟාවන විට ඇසෙන සංඛ්‍යාතය f\' වැඩිවේ (+, -); ඈත්වන විට සංඛ්‍යාතය f\' අඩුවේ (-, +).',
      statObs: 'වචනාර්ථය: නිරීක්ෂකයා නිශ්චල විට (v_o = 0), f\' රඳා පවතින්නේ ධ්වනි ප්‍රවේගය v සහ ප්‍රභවයේ ප්‍රවේගය v_s මත පමණි.',
      mach: 'වචනාර්ථය: මාක් අංකය M > 1 වන විට සුපිරිධ්වනි ගමන සිදු වන අතර මාක් කෝතුවේ කෝණය sin(θ) = 1/M වේ.'
    },

    vars: [
      { sym: "f'", name: 'නිරීක්ෂිත (ඇසෙන) සංඛ්‍යාතය', unit: 'Hz (s⁻¹)' },
      { sym: 'fs', name: 'ප්‍රභවයේ මුල් සංඛ්‍යාතය', unit: 'Hz (s⁻¹)' },
      { sym: 'v', name: 'මාධ්‍යයේ ධ්වනි ප්‍රවේගය', unit: 'm/s' },
      { sym: 'vs', name: 'ප්‍රභවයේ ප්‍රවේගය', unit: 'm/s' },
      { sym: 'vo', name: 'නිරීක්ෂකයාගේ ප්‍රවේගය', unit: 'm/s' },
      { sym: 'λ, λ\'', name: 'සැබෑ සහ ආභාසී තරංග ආයාමය', unit: 'm' },
      { sym: 'M', name: 'මාක් අංකය (vs / v)', unit: 'ඒකක නැත' },
      { sym: 'θ', name: 'මාක් කෝතුවේ අර්ධ කෝණය', unit: 'අංශක' },
    ],

    tipsTitle: 'උසස් පෙළ විභාගයට වැදගත් කරුණු',
    tips: [
      'මාධ්‍ය ප්‍රවේගයේ නියතතාව: ධ්වනි ප්‍රවේගය v රඳා පවතින්නේ මාධ්‍යයේ ස්වභාවය මත පමණි (උදා: වාතයේ 340 m/s). එය ප්‍රභවයේ ප්‍රවේගය v_s මත රඳා නොපවතී.',
      'ප්‍රභව සංඛ්‍යාතයේ නියතතාව: ප්‍රභවය මගින් පිටකරන මුල් සංඛ්‍යාතය f_s නියතව පවතී. වෙනස් වන්නේ නිරීක්ෂකයාට ඇසෙන ආභාසී සංඛ්‍යාතය f\' පමණි.',
      'ගිලන් රථයක් පසුකර යාම: නිශ්චල නිරීක්ෂකයෙකු පසුකර ගිලන් රථයක් යන විට සංඛ්‍යාතය f_ළඟාවන = f_s v / (v - v_s) සිට f_ඈත්වන = f_s v / (v + v_s) දක්වා එකවර ක්ෂණිකව අඩුවේ.'
    ]
  },
  ta: {
    badge: 'அலைகள் மற்றும் ஊசலாட்டங்கள் • குறிப்பேடு',
    notebookMode: 'செயல்திறன் குறிப்பேடு',
    simOnlyMode: 'உருவகப்படுத்துதல் மட்டும்',
    tabTheory: 'கோட்பாடு மற்றும் விதிகள்',
    tabFormulas: 'சமன்பாடுகள் மற்றும் அலகுகள்',
    tabTips: 'தேர்வுக்கான முக்கிய குறிப்புகள்',

    dopplerDefTitle: '1. டாப்ளர் விளைவின் வரைவிலக்கணம்',
    dopplerDefBody: 'அலை முதலுக்கும் பார்வையாளருக்கும் இடையிலான சார்பு இயக்கம் காரணமாக பார்வையாளரால் உணரப்படும் அதிர்வெண் அல்லது அலைநீளத்தின் தோற்ற மாற்றம் டாப்ளர் விளைவு எனப்படும்.',

    wavefrontTitle: '2. அலைமுகங்கள் மற்றும் அலைநீள மாற்றம்',
    wavefrontBody: 'ஒலி வேகம் v கொண்ட ஊடகத்தில் முதல் v_s வேகத்தில் இயங்கும்போது:',
    towardsWave: 'அணுகும் பார்வையாளருக்கு: அலைநீளம் குறைகிறது λ\' = (v - v_s)/f_s.',
    awayWave: 'விலகும் பார்வையாளருக்கு: அலைநீளம் அதிகரிக்கிறது λ\' = (v + v_s)/f_s.',

    sonicBoomTitle: '3. ஒலி அதிர்வு மற்றும் மாக் கூம்பு (v_s ≥ v)',
    sonicBoomBody: 'முதல் வேகம் ஒலியின் வேகத்திற்கு சமமாக அல்லது அதிகமாகும் போது:',
    sonicList: [
      'ஒலி தடுப்புச்சுவர் (v_s = v, மாக் 1): அலைமுகங்கள் முதலின் முன்னால் குவிந்து உயர் அழுத்தத் தடுப்பை உருவாக்குகின்றன.',
      'மீயொலிப் பயணம் (v_s > v, மாக் > 1): முதல் தனது சொந்த அலைகளை விட வேகமாகச் சென்று கூம்பு வடிவ அதிர்ச்சி அலையை (மாக் கூம்பு) உருவாக்குகிறது.',
      'மாக் கூம்புக் கோணம்: sin(θ) = v / v_s = 1 / M (இங்கு M என்பது மாக் எண்).'
    ],

    eqTitle: 'முக்கிய டாப்ளர் பாடத்திட்ட சமன்பாடுகள்',
    generalEq: 'பொது டாப்ளர் சமன்பாடு:',
    varGuideTitle: 'மாறிகள் மற்றும் SI அலகுகள் வழிகாட்டி',

    eqExpl: {
      doppler: 'விளக்கம்: முதலும் பார்வையாளரும் அணுகும்போது உணரப்படும் அதிர்வெண் f\' அதிகரிக்கும்; விலகும்போது குறையும்.',
      statObs: 'விளக்கம்: பார்வையாளர் நிலையாக இருக்கும்போது (v_o = 0), f\' ஒலியின் வேகம் v மற்றும் முதலின் வேகம் v_s இல் தங்கியுள்ளது.',
      mach: 'விளக்கம்: மாக் எண் M > 1 என்பது மீயொலிப் பயணத்தைக் குறிக்கிறது, மாக் கூம்புக் கோணம் sin(θ) = 1/M.'
    },

    vars: [
      { sym: "f'", name: 'உணரப்படும் அதிர்வெண்', unit: 'Hz (s⁻¹)' },
      { sym: 'fs', name: 'முதலின் உண்மையான அதிர்வெண்', unit: 'Hz (s⁻¹)' },
      { sym: 'v', name: 'ஒலியின் வேகம்', unit: 'm/s' },
      { sym: 'vs', name: 'முதலின் வேகம்', unit: 'm/s' },
      { sym: 'vo', name: 'பார்வையாளரின் வேகம்', unit: 'm/s' },
      { sym: 'λ, λ\'', name: 'உண்மையான vs தோற்ற அலைநீளம்', unit: 'm' },
      { sym: 'M', name: 'மாக் எண் (vs / v)', unit: 'அலகற்றது' },
      { sym: 'θ', name: 'மாக் கூம்புக் கோணம்', unit: 'பாகை' },
    ],

    tipsTitle: 'உயர்தர தேர்வுக்கான முக்கிய தகவல்கள்',
    tips: [
      'ஊடக வேகத்தின் மாறாத்தன்மை: ஒலியின் வேகம் v ஊடகத்தின் தன்மையில் மட்டுமே தங்கியுள்ளது (எ.கா. காற்றில் 340 m/s), முதலின் வேகம் v_s இல் அல்ல.',
      'முதல் அதிர்வெண்ணின் மாறாத்தன்மை: முதலின் உண்மையான அதிர்வெண் f_s மாறாது; தோற்ற அதிர்வெண் f\' மட்டுமே சார்பு இயக்கத்தால் மாறுகிறது.',
      'ஆம்புலன்ஸ் கடந்து செல்லும் போது: நிலையான பார்வையாளரைக் கடந்து ஆம்புலன்ஸ் செல்லும்போது அதிர்வெண் உடனடியாகக் குறைகிறது.'
    ]
  }
};

export function DopplerEffectSimulation({ lang = 'en' }: { lang?: 'en' | 'si' | 'ta' }) {
  const TRANSLATIONS = {
    en: {
      title: 'Doppler Effect & Sonic Boom Simulator',
      controls: 'Wave Parameters',
      sourceSpeed: 'Source Speed (vₛ)',
      observerSpeed: 'Observer Speed (vₒ)',
      sourceFreq: 'Source Frequency (fₛ)',
      speedOfSound: 'Speed of Sound (v)',
      soundToggle: 'Audio Synthesizer Pitch Tone',
      audioListener: 'Audio Focus / Listener',
      listenerA: 'Observer 1 (Left)',
      listenerB: 'Observer 2 (Right)',
      listenerSource: 'Source',
      calculations: 'Doppler Frequency Computations',
      formula: "f' = fₛ (v ± vₒ) / (v ∓ vₛ)",
      observedLeft: 'Observed Frequency Left (fₗ)',
      observedRight: 'Observed Frequency Right (fᵣ)',
      sonicBoomAlert: 'SONIC BOOM! (vₛ ≥ v)',
      logTrial: 'Record Frequencies',
      trialHistory: 'Doppler Observations Log',
      labNotes: 'Observation Journal',
      pdf: 'Export PDF',
      audioOn: 'Enable Audio Pitch',
      audioOff: 'Mute Audio',
      machNumber: 'Mach Number (M)'
    },
    si: {
      title: 'ඩොප්ලර් ආචරණය සහ සුපිරිධ්වනි කම්පන තරංග සිමියුලේටරය',
      controls: 'තරංග පරාමිතීන්',
      sourceSpeed: 'ප්‍රභවයේ ප්‍රවේගය (vₛ)',
      observerSpeed: 'නිරීක්ෂකයාගේ ප්‍රවේගය (vₒ)',
      sourceFreq: 'ප්‍රභවයේ සංඛ්‍යාතය (fₛ)',
      speedOfSound: 'ධ්වනි ප්‍රවේගය (v)',
      soundToggle: 'ශ්‍රව්‍ය සංඛ්‍යාත ස්වරය',
      audioListener: 'ශ්‍රව්‍ය අවධානය / නිරීක්ෂකයා',
      listenerA: 'නිරීක්ෂක 1 (වම)',
      listenerB: 'නිරීක්ෂක 2 (දකුණ)',
      listenerSource: 'ප්‍රභවය',
      calculations: 'ඩොප්ලර් සංඛ්‍යාත ගණනය කිරීම්',
      formula: "f' = fₛ (v ± vₒ) / (v ∓ vₛ)",
      observedLeft: 'වම් නිරීක්ෂකයාට ඇසෙන සංඛ්‍යාතය (fₗ)',
      observedRight: 'දකුණු නිරීක්ෂකයාට ඇසෙන සංඛ්‍යාතය (fᵣ)',
      sonicBoomAlert: 'සුපිරිධ්වනි කම්පනය! (vₛ ≥ v)',
      logTrial: 'සංඛ්‍යාත සටහන් කරන්න',
      trialHistory: 'ඩොප්ලර් නිරීක්ෂණ සටහන්',
      labNotes: 'ලැබ් නිරීක්ෂණ සටහන් පොත',
      pdf: 'PDF ලබාගන්න',
      audioOn: 'ශබ්දය සක්‍රිය කරන්න',
      audioOff: 'ශබ්දය අක්‍රිය කරන්න',
      machNumber: 'මාක් අංකය (M)'
    },
    ta: {
      title: 'டாப்ளர் விளைவு & ஒலி அதிர்வு சிமுலேட்டர்',
      controls: 'அலை அளவுருக்கள்',
      sourceSpeed: 'ஒலி மூல வேகம் (vₛ)',
      observerSpeed: 'அவதானிப்பாளர் வேகம் (vₒ)',
      sourceFreq: 'மூல அதிர்வெண் (fₛ)',
      speedOfSound: 'ஒலியின் வேகம் (v)',
      soundToggle: 'ஒலி அதிர்வெண் தொனி',
      audioListener: 'ஒலி அமைவு / அவதானிப்பாளர்',
      listenerA: 'அவதானிப்பாளர் 1 (இடது)',
      listenerB: 'அவதானிப்பாளர் 2 (வலது)',
      listenerSource: 'மூலம்',
      calculations: 'டாப்ளர் அதிர்வெண் கணிப்புகள்',
      formula: "f' = fₛ (v ± vₒ) / (v ∓ vₛ)",
      observedLeft: 'இடது அவதானிப்பாளர் அதிர்வெண் (fₗ)',
      observedRight: 'வலது அவதானிப்பாளர் அதிர்வெண் (fᵣ)',
      sonicBoomAlert: 'ஒலி அதிர்வு அலறல்! (vₛ ≥ v)',
      logTrial: 'அதிர்வெண்களைப் பதிவுசெய்க',
      trialHistory: 'டாப்ளர் சோதனைப் பதிவுகள்',
      labNotes: 'ஆய்வகக் குறிப்பேடு',
      pdf: 'PDF ஏற்றுமதி செய்',
      audioOn: 'ஒலியை இயக்கு',
      audioOff: 'ஒலியை முடக்கு',
      machNumber: 'மேக் எண் (M)'
    }
  };

  const t = TRANSLATIONS[lang] || TRANSLATIONS.en;
  const tn = DOPPLER_THEORY_NOTES[lang] || DOPPLER_THEORY_NOTES.en;
  const [viewMode, setViewMode] = useState<'notebook' | 'sim_only'>('notebook');
  const [activeTheoryTab, setActiveTheoryTab] = useState<'theory' | 'formulas' | 'tips'>('theory');

  // Parameters
  const [sourceSpeed, setSourceSpeed] = useState<number>(120); // m/s
  const [observerSpeedA, setObserverSpeedA] = useState<number>(0); // m/s (Left observer)
  const [observerSpeedB, setObserverSpeedB] = useState<number>(0); // m/s (Right observer)
  const [sourceFreq, setSourceFreq] = useState<number>(400); // Hz
  const [isPlaying, setIsPlaying] = useState<boolean>(true);
  const [isAudioEnabled, setIsAudioEnabled] = useState<boolean>(false);
  const [audioListener, setAudioListener] = useState<'a' | 'b' | 'source'>('b');

  // History tracking for frequency vs time plots
  const [history, setHistory] = useState<{ t: number[]; freqA: number[]; freqB: number[] }>({
    t: [],
    freqA: [],
    freqB: []
  });
  const lastHistoryUpdateRef = useRef<number>(0);
  const startTimeRef = useRef<number>(performance.now());

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const animFrameRef = useRef<number | null>(null);

  // Audio Context references for real-time synthesizer pitch tone
  const audioCtxRef = useRef<AudioContext | null>(null);
  const oscillatorRef = useRef<OscillatorNode | null>(null);
  const gainNodeRef = useRef<GainNode | null>(null);

  const speedOfSound = 340; // m/s (fixed reference)

  // Wavefront parameters
  const wavefrontsRef = useRef<Wavefront[]>([]);
  const lastEmissionTimeRef = useRef<number>(0);
  const sourceXRef = useRef<number>(270); // starts in center
  const nextWavefrontIdRef = useRef<number>(0);

  // Mach Number: M = v_s / v
  const machNumber = useMemo(() => {
    return sourceSpeed / speedOfSound;
  }, [sourceSpeed]);

  // Doppler Calculations
  const observedFreqLeft = useMemo(() => {
    if (sourceSpeed >= speedOfSound) return 0;
    // For Observer A (Left): sound travels left (negative direction).
    // If observer A moves right (towards source, positive velocity): relative speed of waves meeting observer increases.
    // So observed frequency f_A = f_s * (c + v_oA) / (c + v_s)
    return sourceFreq * ((speedOfSound + observerSpeedA) / (speedOfSound + sourceSpeed));
  }, [sourceFreq, sourceSpeed, observerSpeedA]);

  const observedFreqRight = useMemo(() => {
    if (sourceSpeed >= speedOfSound) return Infinity;
    // For Observer B (Right): sound travels right (positive direction).
    // If observer B moves right (away from source, positive velocity): relative speed of waves meeting observer decreases.
    // So observed frequency f_B = f_s * (c - v_oB) / (c - v_s)
    return sourceFreq * ((speedOfSound - observerSpeedB) / (speedOfSound - sourceSpeed));
  }, [sourceFreq, sourceSpeed, observerSpeedB]);

  // Audio effects handling
  useEffect(() => {
    if (isAudioEnabled) {
      try {
        if (!audioCtxRef.current) {
          audioCtxRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
        }
        if (!oscillatorRef.current) {
          const ctx = audioCtxRef.current;
          const osc = ctx.createOscillator();
          const gain = ctx.createGain();

          osc.type = 'sine';
          osc.frequency.setValueAtTime(sourceFreq, ctx.currentTime);
          gain.gain.setValueAtTime(0.08, ctx.currentTime); // keep volume low

          osc.connect(gain);
          gain.connect(ctx.destination);
          osc.start();

          oscillatorRef.current = osc;
          gainNodeRef.current = gain;
        }
      } catch (e) {
        console.warn('Web Audio Context initialization blocked/failed', e);
      }
    } else {
      if (oscillatorRef.current) {
        try {
          oscillatorRef.current.stop();
        } catch(e){}
        oscillatorRef.current = null;
      }
      if (audioCtxRef.current) {
        audioCtxRef.current.close().then(() => {
          audioCtxRef.current = null;
        });
      }
    }

    return () => {
      if (oscillatorRef.current) {
        try { oscillatorRef.current.stop(); } catch(e){}
      }
    };
  }, [isAudioEnabled]);

  // Update sound synthesizer pitch real-time following active observer focus selection
  useEffect(() => {
    if (isAudioEnabled && oscillatorRef.current && audioCtxRef.current) {
      let displayPitch = sourceFreq;
      if (audioListener === 'a') {
        displayPitch = observedFreqLeft;
      } else if (audioListener === 'b') {
        displayPitch = sourceSpeed >= speedOfSound ? 0 : observedFreqRight;
      }
      if (isFinite(displayPitch) && displayPitch > 0) {
        oscillatorRef.current.frequency.setValueAtTime(displayPitch, audioCtxRef.current.currentTime);
      }
    }
  }, [observedFreqLeft, observedFreqRight, sourceFreq, sourceSpeed, isAudioEnabled, audioListener]);

  const handleReset = () => {
    setSourceSpeed(120);
    setObserverSpeedA(0);
    setObserverSpeedB(0);
    setSourceFreq(400);
    setIsPlaying(true);
    setAudioListener('b');
    sourceXRef.current = 270;
    wavefrontsRef.current = [];
    setHistory({ t: [], freqA: [], freqB: [] });
    startTimeRef.current = performance.now();
    lastHistoryUpdateRef.current = 0;
  };

  // Universal Simulation Data Recorder & Laboratory Transfer
  const recorder = useSimulationRecorder({
    simulationId: 'doppler_sim',
    simulationTitle: 'Doppler Effect & Wavefront Analysis',
    category: 'waves',
    columns: [
      { key: 'trial', label: 'Trial #' },
      { key: 'sourceSpeed', label: 'Source Speed (vₛ)', unit: 'm/s' },
      { key: 'sourceFreq', label: 'Source Frequency (fₛ)', unit: 'Hz' },
      { key: 'speedOfSound', label: 'Speed of Sound (v)', unit: 'm/s' },
      { key: 'observedFreqRight', label: 'Observed Freq Right (fᵣ)', unit: 'Hz' },
      { key: 'observedFreqLeft', label: 'Observed Freq Left (fₗ)', unit: 'Hz' },
      { key: 'machNumber', label: 'Mach Number (M)', unit: '' },
    ],
    getCurrentRow: () => {
      const fRight = sourceSpeed >= speedOfSound ? 9999 : parseFloat(observedFreqRight.toFixed(1));
      const fLeft = parseFloat(observedFreqLeft.toFixed(1));
      const mach = parseFloat((sourceSpeed / speedOfSound).toFixed(2));
      return {
        sourceSpeed,
        sourceFreq,
        speedOfSound,
        observedFreqRight: fRight,
        observedFreqLeft: fLeft,
        machNumber: mach,
      };
    },
    getSeriesData: () => {
      const speeds = [0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300];
      return speeds.map((spd, idx) => {
        const fR = spd >= speedOfSound ? 9999 : sourceFreq * ((speedOfSound - observerSpeedB) / (speedOfSound - spd));
        const fL = sourceFreq * ((speedOfSound + observerSpeedA) / (speedOfSound + spd));
        return {
          trial: idx + 1,
          sourceSpeed: spd,
          sourceFreq,
          speedOfSound,
          observedFreqRight: parseFloat(fR.toFixed(1)),
          observedFreqLeft: parseFloat(fL.toFixed(1)),
          machNumber: parseFloat((spd / speedOfSound).toFixed(2)),
        };
      });
    },
    autoRunConfig: {
      steps: [
        { label: 'Source Speed vₛ = 0 m/s', params: { sourceSpeed: 0 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 50 m/s', params: { sourceSpeed: 50 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 100 m/s', params: { sourceSpeed: 100 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 150 m/s', params: { sourceSpeed: 150 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 200 m/s', params: { sourceSpeed: 200 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 250 m/s', params: { sourceSpeed: 250 }, durationMs: 750 },
        { label: 'Source Speed vₛ = 300 m/s', params: { sourceSpeed: 300 }, durationMs: 750 },
      ],
      applyParams: (p) => {
        if (p.sourceSpeed !== undefined) setSourceSpeed(p.sourceSpeed);
      },
    },
    defaultGraphConfig: {
      xAxis: 'sourceSpeed',
      yAxis: 'observedFreqRight',
      title: "Doppler Effect: Observed Frequency f' vs Source Speed vₛ",
      showRegression: false,
    },
  });

  // Rendering wavefront propagation loops
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const dpr = window.devicePixelRatio || 1;
    const rectWidth = 540;
    const rectHeight = 240;

    canvas.width = rectWidth * dpr;
    canvas.height = rectHeight * dpr;
    canvas.style.width = `${rectWidth}px`;
    canvas.style.height = `${rectHeight}px`;

    let lastTime = performance.now();

    const loop = (time: number) => {
      const dt = Math.min(0.04, (time - lastTime) / 1000);
      lastTime = time;

      // Update graph history periodically
      if (isPlaying) {
        const nowMs = time;
        if (nowMs - lastHistoryUpdateRef.current >= 120) {
          setHistory(prev => {
            const nextT = [...prev.t, parseFloat(((nowMs - startTimeRef.current) / 1000).toFixed(1))];
            const nextA = [...prev.freqA, observedFreqLeft];
            const nextB = [...prev.freqB, sourceSpeed >= speedOfSound ? 0 : observedFreqRight];
            if (nextT.length > 50) {
              nextT.shift();
              nextA.shift();
              nextB.shift();
            }
            return { t: nextT, freqA: nextA, freqB: nextB };
          });
          lastHistoryUpdateRef.current = nowMs;
        }
      }

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.save();
      ctx.scale(dpr, dpr);

      // Draw background grid lines
      ctx.strokeStyle = '#f8fafc';
      ctx.lineWidth = 1;
      for (let x = 0; x < rectWidth; x += 30) {
        ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, rectHeight); ctx.stroke();
      }
      for (let y = 0; y < rectHeight; y += 30) {
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(rectWidth, y); ctx.stroke();
      }

      // Draw Observers
      // Left Observer (Observer A) at x = 40
      ctx.fillStyle = '#475569';
      ctx.beginPath(); ctx.arc(40, rectHeight / 2, 8, 0, 2 * Math.PI); ctx.fill();
      ctx.fillStyle = '#0f172a';
      ctx.font = 'bold 10px font-sans';
      ctx.fillText('Obs A (Left)', 20, rectHeight / 2 - 15);

      // Right Observer (Observer B) at x = 500
      ctx.fillStyle = '#475569';
      ctx.beginPath(); ctx.arc(500, rectHeight / 2, 8, 0, 2 * Math.PI); ctx.fill();
      ctx.fillText('Obs B (Right)', 460, rectHeight / 2 - 15);

      // Draw observer velocity arrows
      // Draw Observer A velocity arrow
      if (observerSpeedA !== 0) {
        ctx.strokeStyle = '#10b981';
        ctx.fillStyle = '#10b981';
        ctx.lineWidth = 2;
        const arrowLength = observerSpeedA * 0.45;
        ctx.beginPath();
        ctx.moveTo(40, rectHeight / 2 + 15);
        ctx.lineTo(40 + arrowLength, rectHeight / 2 + 15);
        ctx.stroke();

        ctx.beginPath();
        const dirA = Math.sign(observerSpeedA);
        ctx.moveTo(40 + arrowLength, rectHeight / 2 + 15);
        ctx.lineTo(40 + arrowLength - 4 * dirA, rectHeight / 2 + 12);
        ctx.lineTo(40 + arrowLength - 4 * dirA, rectHeight / 2 + 18);
        ctx.fill();
      }

      // Draw Observer B velocity arrow
      if (observerSpeedB !== 0) {
        ctx.strokeStyle = '#10b981';
        ctx.fillStyle = '#10b981';
        ctx.lineWidth = 2;
        const arrowLength = observerSpeedB * 0.45;
        ctx.beginPath();
        ctx.moveTo(500, rectHeight / 2 + 15);
        ctx.lineTo(500 + arrowLength, rectHeight / 2 + 15);
        ctx.stroke();

        ctx.beginPath();
        const dirB = Math.sign(observerSpeedB);
        ctx.moveTo(500 + arrowLength, rectHeight / 2 + 15);
        ctx.lineTo(500 + arrowLength - 4 * dirB, rectHeight / 2 + 12);
        ctx.lineTo(500 + arrowLength - 4 * dirB, rectHeight / 2 + 18);
        ctx.fill();
      }

      if (isPlaying) {
        // Move source to the right
        const scalePixelsPerMeter = 0.55; // visual mapping scale
        sourceXRef.current += sourceSpeed * scalePixelsPerMeter * dt;

        // Wrap source when exiting canvas bounds
        if (sourceXRef.current > 510) {
          sourceXRef.current = 30;
          wavefrontsRef.current = []; // flush loops on wrap
        }

        // Periodic emission of wavefronts
        const emissionInterval = 1 / (sourceFreq / 100); // scaled frequency spacing
        if (time - lastEmissionTimeRef.current >= emissionInterval * 1000) {
          wavefrontsRef.current.push({
            id: nextWavefrontIdRef.current++,
            x: sourceXRef.current,
            y: rectHeight / 2,
            radius: 0,
            timeElapsed: 0
          });
          lastEmissionTimeRef.current = time;
        }

        // Propagate wavefront radius at speed of sound (v)
        wavefrontsRef.current.forEach(w => {
          w.radius += speedOfSound * scalePixelsPerMeter * dt;
          w.timeElapsed += dt;
        });

        // Filter out very large wavefronts off-screen
        wavefrontsRef.current = wavefrontsRef.current.filter(w => w.radius < 450);
      }

      // Draw wavefront circles
      ctx.strokeStyle = 'rgba(59, 130, 246, 0.4)';
      ctx.lineWidth = 1.5;
      wavefrontsRef.current.forEach(w => {
        ctx.beginPath();
        ctx.arc(w.x, w.y, w.radius, 0, 2 * Math.PI);
        ctx.stroke();

        // Highlight Mach shock wave cone (tangents) if supersonic
        if (machNumber >= 1.0) {
          ctx.fillStyle = 'rgba(239, 68, 68, 0.05)';
          ctx.beginPath();
          ctx.arc(w.x, w.y, w.radius, 0, 2 * Math.PI);
          ctx.fill();
        }
      });

      // Draw Mach Shockwave Cone line overlays if supersonic
      if (machNumber > 1.0 && wavefrontsRef.current.length > 5) {
        ctx.strokeStyle = '#ef4444';
        ctx.lineWidth = 2.5;
        const alpha = Math.asin(1 / machNumber); // Mach angle
        
        ctx.beginPath();
        ctx.moveTo(sourceXRef.current, rectHeight / 2);
        ctx.lineTo(sourceXRef.current - 180 * Math.cos(alpha), rectHeight / 2 - 180 * Math.sin(alpha));
        ctx.moveTo(sourceXRef.current, rectHeight / 2);
        ctx.lineTo(sourceXRef.current - 180 * Math.cos(alpha), rectHeight / 2 + 180 * Math.sin(alpha));
        ctx.stroke();
      }

      // Draw Sound Source (Siren Vehicle)
      ctx.fillStyle = '#ef4444';
      ctx.beginPath();
      ctx.arc(sourceXRef.current, rectHeight / 2, 7, 0, 2 * Math.PI);
      ctx.fill();
      
      ctx.fillStyle = '#1e293b';
      ctx.font = 'bold 9px font-sans';
      ctx.fillText(`Source (vₛ)`, sourceXRef.current - 22, rectHeight / 2 + 20);

      ctx.restore();
      animFrameRef.current = requestAnimationFrame(loop);
    };

    animFrameRef.current = requestAnimationFrame(loop);
    return () => {
      if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
    };
  }, [isPlaying, sourceSpeed, sourceFreq, machNumber, observerSpeedA, observerSpeedB, observedFreqLeft, observedFreqRight]);

  return (
    <div className="max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      
      {/* Header & View Mode Selector */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 bg-blue-50 border border-blue-100 rounded-full text-[10px] font-black uppercase tracking-wider text-blue-700 mb-1">
            <Sparkles className="w-3 h-3 text-blue-600" />
            {tn.badge}
          </div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight">
            {t.title}
          </h2>
        </div>

        {/* View Mode Toggle Pill Buttons */}
        <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-xl shrink-0 self-start sm:self-auto">
          <button
            onClick={() => setViewMode('notebook')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer ${
              viewMode === 'notebook'
                ? 'bg-white text-blue-600 shadow-xs font-extrabold'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5" />
            <span>{tn.notebookMode}</span>
          </button>
          <button
            onClick={() => setViewMode('sim_only')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer ${
              viewMode === 'sim_only'
                ? 'bg-white text-indigo-600 shadow-xs font-extrabold'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            <Maximize2 className="w-3.5 h-3.5" />
            <span>{tn.simOnlyMode}</span>
          </button>
        </div>
      </div>

      {/* INTERACTIVE THEORY NOTEBOOK CARD (Visible in Notebook Mode) */}
      {viewMode === 'notebook' && (
        <div className="bg-white border border-blue-100 rounded-2xl p-6 shadow-sm space-y-5">
          {/* Notebook Tabs */}
          <div className="flex flex-wrap items-center gap-2 border-b border-slate-100 pb-3">
            <button
              onClick={() => setActiveTheoryTab('theory')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-extrabold transition-all flex items-center gap-1.5 cursor-pointer ${
                activeTheoryTab === 'theory'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>{tn.tabTheory}</span>
            </button>
            <button
              onClick={() => setActiveTheoryTab('formulas')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-extrabold transition-all flex items-center gap-1.5 cursor-pointer ${
                activeTheoryTab === 'formulas'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              <Activity className="w-3.5 h-3.5" />
              <span>{tn.tabFormulas}</span>
            </button>
            <button
              onClick={() => setActiveTheoryTab('tips')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-extrabold transition-all flex items-center gap-1.5 cursor-pointer ${
                activeTheoryTab === 'tips'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              <Lightbulb className="w-3.5 h-3.5 text-amber-300" />
              <span>{tn.tabTips}</span>
            </button>
          </div>

          {/* Tab 1: Theory & Physical Laws */}
          {activeTheoryTab === 'theory' && (
            <div className="space-y-4 text-xs text-slate-700 leading-relaxed">
              <div className="bg-slate-50 border-l-4 border-blue-600 p-4 rounded-r-xl space-y-1.5">
                <h3 className="font-extrabold text-slate-900 text-sm">{tn.dopplerDefTitle}</h3>
                <p>{tn.dopplerDefBody}</p>
              </div>

              <div className="bg-white border border-slate-200 rounded-xl p-4 space-y-2">
                <h4 className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-indigo-600"></span>
                  {tn.wavefrontTitle}
                </h4>
                <p>{tn.wavefrontBody}</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
                  <div className="bg-emerald-50/60 border border-emerald-100 p-3 rounded-lg text-emerald-900 font-medium">
                    {tn.towardsWave}
                  </div>
                  <div className="bg-amber-50/60 border border-amber-100 p-3 rounded-lg text-amber-900 font-medium">
                    {tn.awayWave}
                  </div>
                </div>
              </div>

              <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-4 space-y-2">
                <h4 className="font-bold text-slate-900 text-xs">{tn.sonicBoomTitle}</h4>
                <p>{tn.sonicBoomBody}</p>
                <ul className="list-disc list-inside space-y-1 pl-1 text-slate-600">
                  {tn.sonicList.map((item, idx) => (
                    <li key={idx}>{item}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {/* Tab 2: Equations & SI Units */}
          {activeTheoryTab === 'formulas' && (
            <div className="space-y-5">
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider">{tn.eqTitle}</h3>
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-4">
                <h4 className="font-bold text-blue-700 text-xs">{tn.generalEq}</h4>
                <div>
                  <BlockMath math="f' = f_s \left( \frac{v \pm v_o}{v \mp v_s} \right)" />
                  <p className="text-[11px] text-slate-600 bg-white p-2.5 rounded-lg border border-slate-200 mt-1">{tn.eqExpl.doppler}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs pt-1">
                  <div className="bg-white border border-slate-200 p-3 rounded-xl space-y-2">
                    <span className="font-bold text-slate-800">Stationary Observer (v_o = 0):</span>
                    <BlockMath math="f' = f_s \left( \frac{v}{v \mp v_s} \right)" />
                    <p className="text-[11px] text-slate-600 bg-slate-50 p-2 rounded border border-slate-150">{tn.eqExpl.statObs}</p>
                  </div>
                  <div className="bg-white border border-slate-200 p-3 rounded-xl space-y-2">
                    <span className="font-bold text-slate-800">Mach Number & Cone Angle:</span>
                    <BlockMath math="M = \frac{v_s}{v}, \quad \sin(\theta) = \frac{1}{M}" />
                    <p className="text-[11px] text-slate-600 bg-slate-50 p-2 rounded border border-slate-150">{tn.eqExpl.mach}</p>
                  </div>
                </div>
              </div>

              {/* Variables & SI Units Reference Card */}
              <div className="bg-gradient-to-r from-blue-50/80 to-indigo-50/80 border border-blue-100 rounded-xl p-4 space-y-3">
                <h4 className="font-bold text-slate-900 text-xs uppercase tracking-wider flex items-center gap-1.5 text-blue-800">
                  <FileText className="w-4 h-4 text-blue-600" />
                  {tn.varGuideTitle}
                </h4>
                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2 text-xs">
                  {tn.vars.map((v, idx) => (
                    <div key={idx} className="bg-white/80 border border-blue-100 p-2 rounded-lg space-y-0.5">
                      <div className="font-bold text-blue-700 font-mono text-[11px]">{v.sym}</div>
                      <div className="text-slate-800 font-medium text-[11px]">{v.name}</div>
                      <div className="text-[10px] text-slate-400 font-mono font-bold">SI: {v.unit}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Tab 3: Exam Insights */}
          {activeTheoryTab === 'tips' && (
            <div className="space-y-3">
              <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wider flex items-center gap-1.5">
                <Lightbulb className="w-4 h-4 text-amber-500" />
                {tn.tipsTitle}
              </h3>
              <div className="space-y-2.5">
                {tn.tips.map((tip, idx) => (
                  <div key={idx} className="flex items-start gap-2.5 bg-amber-50/60 border border-amber-200/60 p-3 rounded-xl text-xs text-amber-900 font-medium">
                    <CheckCircle2 className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <span>{tip}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 flex-1 min-h-0">
        
        {/* Parameters controls (4 Cols) */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-5">
            <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
              <h3 className="font-extrabold text-sm text-slate-800 tracking-tight uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-blue-600" />
                {t.controls}
              </h3>
              <span className="text-[9px] text-slate-450 font-bold uppercase">Acoustic Lab</span>
            </div>

            {/* Source speed */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-bold">
                <span className="text-slate-600">{t.sourceSpeed}</span>
                <span className="text-slate-850 font-mono">{sourceSpeed} m/s</span>
              </div>
              <input
                type="range"
                min="0"
                max="400"
                step="10"
                value={sourceSpeed}
                disabled={recorder.isAutoRunning}
                onChange={(e) => setSourceSpeed(parseInt(e.target.value))}
                className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              />
            </div>

            {/* Observer A speed */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-bold">
                <span className="text-slate-650">{lang === 'en' ? 'Obs A Speed (Left)' : lang === 'si' ? 'නිරීක්ෂක A ප්‍රවේගය' : 'அவதானிப்பாளர் A வேகம்'}</span>
                <span className="text-slate-850 font-mono">{observerSpeedA} m/s</span>
              </div>
              <input
                type="range"
                min="-100"
                max="100"
                step="5"
                value={observerSpeedA}
                disabled={recorder.isAutoRunning}
                onChange={(e) => setObserverSpeedA(parseInt(e.target.value))}
                className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              />
            </div>

            {/* Observer B speed */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-bold">
                <span className="text-slate-650">{lang === 'en' ? 'Obs B Speed (Right)' : lang === 'si' ? 'නිරීක්ෂක B ප්‍රවේගය' : 'அவதானிப்பாளர் B வேகம்'}</span>
                <span className="text-slate-850 font-mono">{observerSpeedB} m/s</span>
              </div>
              <input
                type="range"
                min="-100"
                max="100"
                step="5"
                value={observerSpeedB}
                disabled={recorder.isAutoRunning}
                onChange={(e) => setObserverSpeedB(parseInt(e.target.value))}
                className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              />
            </div>

            {/* Source frequency */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-bold">
                <span className="text-slate-600">{t.sourceFreq}</span>
                <span className="text-slate-850 font-mono">{sourceFreq} Hz</span>
              </div>
              <input
                type="range"
                min="200"
                max="800"
                step="25"
                value={sourceFreq}
                disabled={recorder.isAutoRunning}
                onChange={(e) => setSourceFreq(parseInt(e.target.value))}
                className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              />
            </div>

            {/* Audio Listener Focus Selector */}
            <div className="space-y-1.5 pt-2 border-t border-slate-100">
              <label className="text-[10px] font-bold text-slate-405 uppercase tracking-wider block">
                {t.audioListener}
              </label>
              <div className="flex gap-1.5">
                <button
                  onClick={() => setAudioListener('a')}
                  className={`flex-1 py-1 rounded text-[10px] font-bold border transition-all cursor-pointer ${
                    audioListener === 'a'
                      ? 'bg-slate-800 border-slate-900 text-white'
                      : 'bg-white border-slate-200 text-slate-650 hover:bg-slate-50'
                  }`}
                >
                  {t.listenerA}
                </button>
                <button
                  onClick={() => setAudioListener('b')}
                  className={`flex-1 py-1 rounded text-[10px] font-bold border transition-all cursor-pointer ${
                    audioListener === 'b'
                      ? 'bg-slate-800 border-slate-900 text-white'
                      : 'bg-white border-slate-200 text-slate-650 hover:bg-slate-50'
                  }`}
                >
                  {t.listenerB}
                </button>
                <button
                  onClick={() => setAudioListener('source')}
                  className={`flex-1 py-1 rounded text-[10px] font-bold border transition-all cursor-pointer ${
                    audioListener === 'source'
                      ? 'bg-slate-800 border-slate-900 text-white'
                      : 'bg-white border-slate-200 text-slate-650 hover:bg-slate-50'
                  }`}
                >
                  {t.listenerSource}
                </button>
              </div>
            </div>

            {/* Synthesizer Pitch Audio button */}
            <div className="space-y-1.5 pt-2 border-t border-slate-100">
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">{t.soundToggle}</label>
              <button
                onClick={() => setIsAudioEnabled(!isAudioEnabled)}
                className={`w-full py-2 px-3 text-xs font-bold rounded-lg border transition-all flex items-center justify-center gap-2 cursor-pointer ${
                  isAudioEnabled 
                    ? 'bg-blue-600 border-blue-650 text-white shadow-sm' 
                    : 'bg-white border-slate-200 text-slate-650 hover:bg-slate-50'
                }`}
              >
                {isAudioEnabled ? <Volume2 className="w-4 h-4" /> : <VolumeX className="w-4 h-4" />}
                {isAudioEnabled ? t.audioOff : t.audioOn}
              </button>
            </div>

            {/* Action buttons */}
            <div className="flex gap-2 pt-2 border-t border-slate-100">
              <button
                onClick={recorder.recordTrial}
                className="flex-1 py-1.5 bg-slate-900 hover:bg-slate-850 text-white rounded-lg text-[10px] font-black uppercase tracking-wider flex items-center justify-center gap-1 transition-colors cursor-pointer"
              >
                <Plus className="w-3 h-3" />
                {t.logTrial}
              </button>
              <button
                onClick={handleReset}
                className="p-1.5 bg-slate-100 hover:bg-slate-200 text-slate-650 rounded-lg transition-colors cursor-pointer"
                title="Reset simulation parameters"
              >
                <RotateCcw className="w-3.5 h-3.5" />
              </button>
            </div>

          </div>
        </div>

        {/* Right visualizer viewport (8 Cols) */}
        <div className="lg:col-span-8 flex flex-col gap-6">
          <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm flex flex-col items-center relative">
            <div className="flex items-center justify-between w-full mb-2">
              <h3 className="text-xs font-black text-slate-400 uppercase tracking-wider">
                {t.title}
              </h3>
              
              <div className="flex items-center gap-1.5 bg-slate-50 border border-slate-100 rounded-lg p-0.5">
                <button
                  onClick={() => setIsPlaying(!isPlaying)}
                  className="p-1 hover:bg-slate-200/60 rounded text-slate-700 transition-colors cursor-pointer"
                >
                  {isPlaying ? <Pause className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            <div className="w-full flex justify-center py-2 relative">
              <canvas
                ref={canvasRef}
                className="border border-slate-100 rounded-xl bg-white select-none shadow-sm"
              />

              {/* Mach shock wave warning banner */}
              {machNumber >= 1.0 && (
                <div className="absolute top-4 left-4 bg-red-600 border border-red-700 text-white font-extrabold text-[10px] uppercase px-3 py-1 rounded shadow-md animate-pulse">
                  {t.sonicBoomAlert}
                </div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
            {/* Doppler values */}
            <div className="md:col-span-5 bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-4">
              <h4 className="text-xs font-extrabold text-slate-800 uppercase tracking-wider border-b border-slate-100 pb-2">
                {t.calculations}
              </h4>
              
              <div className="space-y-2.5 text-xs">
                <div className="flex justify-between font-medium">
                  <span className="text-slate-500">{t.speedOfSound}:</span>
                  <span className="font-mono text-slate-800 font-bold">{speedOfSound} m/s</span>
                </div>
                <div className="flex justify-between font-medium">
                  <span className="text-slate-500">{t.machNumber}:</span>
                  <span className="font-mono text-slate-800 font-bold">{machNumber.toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-medium border-t border-slate-100 pt-2">
                  <span className="text-slate-500">{t.observedLeft}:</span>
                  <span className="font-mono text-emerald-600 font-extrabold">
                    {observedFreqLeft.toFixed(1)} Hz
                  </span>
                </div>
                <div className="flex justify-between font-medium">
                  <span className="text-slate-500">{t.observedRight}:</span>
                  <span className="font-mono text-blue-600 font-extrabold">
                    {sourceSpeed >= speedOfSound ? '∞ (Sonic Boom)' : `${observedFreqRight.toFixed(1)} Hz`}
                  </span>
                </div>
              </div>
            </div>

            {/* Doppler equations */}
            <div className="md:col-span-7 bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-2.5 text-xs text-slate-650 font-medium">
              <h4 className="text-xs font-extrabold text-slate-800 uppercase tracking-wider border-b border-slate-100 pb-2">
                Doppler Wave Theory
              </h4>
              <p>
                The observed frequency <InlineMath math="f'" /> changes because the source motion alters the wavelength of sound waves in the transmission medium:
              </p>
              <BlockMath math="f' = f_s \left( \frac{v \pm v_o}{v \mp v_s} \right)" />
              <p>
                When the source speed reaches the speed of sound (<InlineMath math="v_s = v" />), wave crests merge on top of one another to produce a high-amplitude shock cone.
              </p>
            </div>
          </div>

          {/* Scientific Graph Laboratory */}
          <ScientificGraphLab
            graphs={dopplerEffectGraphs}
            trials={recorder.recordedRows}
            realtimePoints={history.t.map((tVal, i) => ({ t: tVal, x: tVal, y: history.freqB[i], observedFreqA: history.freqA[i], observedFreqB: history.freqB[i] }))}
            simulationParams={{ sourceSpeed, observerSpeed: observerSpeedB, sourceFreq, speedOfSound: 340 }}
            onRecordTrial={recorder.recordTrial}
            onClearTrials={recorder.clearTrials}
            columns={recorder.columns}
            height={260}
          />
        </div>

      </div>

    </div>
  );
}
